REVOKE EXECUTE ON FUNCTION public.building_property_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.floor_property_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_vendor_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_org_member(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_property_owner(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_vendor_owner(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pm_can_manage_property(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pm_can_view_owner_finances(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pm_can_view_property(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pm_is_tenant_of_property(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pm_is_tenant_of_unit(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_property_owner(uuid, uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.building_property_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.floor_property_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_vendor_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_org_member(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_vendor_owner(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pm_can_manage_property(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pm_can_view_owner_finances(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pm_can_view_property(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pm_is_tenant_of_property(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pm_is_tenant_of_unit(uuid, uuid) TO authenticated;